services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017/fuel-tracker
      API_TOKEN: ${API_TOKEN}
      PORT: 3000

volumes:
  mongo-data:
